### ISSUE TITLE
We could add an even more informative and dropdown based navbar components in addition to the ones already present.

### ISSUE THREAD

**Issue by Preet538-neitzen** [cruip/open-react-template#10]
In depth, I propose to add new buttons which on hovering displays a drop-down. 
Example can be seen of the said navbar here: http://taxvisor.in/
I think it would be a good addition.
If you agree, I would love to add this feature in your template.

**Comment by pasqualevitiello** [comment]
Thank you for such a feature request, we'll consider adding it in a future release.
