### ISSUE TITLE
feat-UI is overlapping on mobile view

### ISSUE THREAD

**Issue by Zeba286roohi** [cruip/open-react-template#118]
![image](https://github.com/cruip/open-react-template/assets/85834320/a4567c1b-7ef4-4f9e-a68b-5082b3be702f)

**Features need to fix.**
>Bootstrap landing page is overlapping with logo
>Search box is is overlapping with admin dashboard box.

Assign me this issue to work.

**Comment by pasqualevitiello** [comment]
This integration has nothing to do with the template. Issue closed.
