### ISSUE TITLE
Chrome <54 = Uncaught TypeError: Object [object HTMLImageElement] has no method 'before' Image.js:47

### ISSUE THREAD

**Issue by maxmag-soft** [cruip/open-react-template#17]
This error shows up even with lastest "import 'core-js';"

Chrome 30.0.1573.2 fails to process
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before
.before() olny works with Chrome >54
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
.insertAdjacentHTML('beforebegin') works with Chrome >1

below is my suggestion:
```javascript
  const handlePlaceholder = (img) => {
    const placeholder = document.createElement('img');
    if (!loaded) {
      img.style.display = 'none';
      img.before(placeholder);
      placeholder.src = placeholderSrc(
```
change to:
```javascript
  const handlePlaceholder = (img) => {
    if (!loaded) {
      img.style.display = 'none';
      var randomid = 'r'+Math.floor(Math.random() * 10000);
      img.insertAdjacentHTML('beforebegin','<img class="random-'+randomid+'" src="data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+img.getAttribute('width')+' '+img.getAttribute('height')+'"%3E%3C/svg%3E" width="'+img.getAttribute('width')+'" height="'+img.getAttribute('height')+'">')
      const placeholder = document.querySelector('img.random-'+randomid)
      placeholder.src = placeholderSrc(```

**Comment by pasqualevitiello** [comment]
Thanks for your suggestion! Chrome 54 was released in 2016: https://chromereleases.googleblog.com/2016/10/stable-channel-update-for-desktop.html and looking at usage statistics, it seems that less than 1% uses Chrome <54.
