### ISSUE TITLE
Change text-color-primary and bg-color

### ISSUE THREAD

**Issue by jerrywebman** [cruip/open-react-template#19]
Hi, I am new to scss. I have been struggling for hours on how to change the background color and text color. Could you please show me where I can locate this colors?

Thank you.

**Comment by pasqualevitiello** [comment]
Hi @jerrywebman, this is the color palette: https://github.com/cruip/open-react-template/blob/master/src/assets/scss/settings/base/_colors.scss#L4

You can change the typography color scheme in this array: https://github.com/cruip/open-react-template/blob/master/src/assets/scss/settings/base/_colors.scss#L35

And bg colors in this one: https://github.com/cruip/open-react-template/blob/master/src/assets/scss/settings/base/_colors.scss#L77
