### ISSUE TITLE
Deploy to GH-Pages 

### ISSUE THREAD

**Issue by RELNO** [cruip/open-react-template#22]
@pasqualevitiello @puneetsingh13 thanks for a great project! 

I came across an issue when trying to deploy to `gh-pages`. Note: This is **not** an issue with your code, but a common problem related `gh-pages` when using `react-router-dom`. The solution is to use `HashRouter` to tell the router to keep looking inside the current gh-pages path, so that `App.js` `return` looks something like this:
```
 <ScrollReveal
      ref={childRef}
      children={() => (
        <HashRouter basename="/">
        <Switch>
          <AppRoute exact path="/" component={Home} layout={LayoutDefault} />
        </Switch>
        </HashRouter>
      )} />

```
 This is well described here: https://medium.com/@bennirus/deploying-a-create-react-app-with-routing-to-github-pages-f386b6ce84c2 and I thought you might consider adding this to your readme.

**Comment by pasqualevitiello** [comment]
Cool! Thank you for advising :)
