### ISSUE TITLE
How to have new routes ?

### ISSUE THREAD

**Issue by kopax** [cruip/open-react-template#27]
Hello and thanks for sharing this layout which will definitely help a few.

I am reading your source code and tried to add a new route and a link for it in the menu using `react-router-dom`.

The route works fine, except when I refresh, the content between the header and the footer is hidden, I have to trigger the route once more to get the content displayed. It work fine on the landing page. Using that layout, is it possible to have other route always display their content, especially when doing F5 ?

Thanks a lot for sharing!

**Comment by pasqualevitiello** [comment]
Hello kopax,

Not sure why you are trying to add a second router. Anyway, issue may deal with scroll-reveal animations, please see: https://github.com/cruip/open-react-template/blob/master/src/App.js#L35

**Comment by kopax** [comment]
@pasqualevitiello , I am not trying to add a second router, I am trying to use it by implementing a second route such as `/contact-us` or `/documentation` as in the template whicj shows links but is at the moment just a single route. If you don't need routing why use react router ?

I have already investigayed `ScrollReveal` so this line here specifically doesn't help.

Do you have another hint ? Thanks a lot

**Comment by pasqualevitiello** [comment]
Now I get what you mean :)

1. Create a new page in src/views/ (eg: src/views/Contact.js)
2. Import that file in App.jd (eg: import Contact from './views/Contact';)
3. Add a new route like this: <AppRoute exact path="/contact" component={Contact} layout={LayoutDefault} />

**Comment by kopax** [comment]
Hi, point 3 is missing, if you were going to show me the same snippet, then there's something wrong about it.

If I click from `Home` -> `Contact`, then the contact get displayed.

If I press `F5` (refresh), then the `Contact` doesn't display, I have tried to find a way to trigger the appearing event, but nothing so far makes it work, one way is to disable it. If after refreshing you click on the `Contact` link again, then it appear.

I don't see how it can be good to provide the contact page link to someone and have nothing being displayed unless he navigate, if you know how I can get over this  issue, I will be grateful. Thanks.

**Comment by pasqualevitiello** [comment]
Now you should be able to see point 3 :) you shouldn't use the `<ScrollReveal />` component more than once.

**Comment by kopax** [comment]
As you can see in my example, I did create my route exactly as in point 3.

If the ScrollReveal should not be used more than once, why is it wrapping the application Switch ? How should I reuse it ? What will trigger the animation without it ? Can't I just run the reveal ?

**Comment by pasqualevitiello** [comment]
It was meant to be a "wrapper" with JS functionalities (https://github.com/cruip/open-react-template/blob/master/src/utils/ScrollReveal.js). 

Anyway, you are doing something wrong, because I've just tried and it works. Please see: https://www.loom.com/share/be6bd80107704e549d4ff54b153b0cc4

Finally, please note that Open was meant to be a one-page template, and the wrapping CRA ecosystem was just a way to get users into the development process. Unfortunately any kind of customisation is out of the support scope, hope you can understand.

**Comment by kopax** [comment]
Hi @pasqualevitiello , yes I totally understand.

I finally found why it was not working in my code template as I am having the exact same code as you except for the application splitting where I use `react-loadable` to split on route change, this was the export of `ContactUs.js`

```jsx
import Loadable from 'react-loadable';

export default Loadable({
  loader: () => import('./ContactUs'),
});
```

I understand that this is not of your concern and there's no support behind open, I am just reporting for others, if a page is loaded up asynchronously, then things won't work.
