### ISSUE TITLE
Outdate node-sass will throw an error during is npm install

### ISSUE THREAD

**Issue by the-black-viper** [cruip/open-react-template#28]
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-88_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-88_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234
```

**Comment by the-black-viper** [comment]
Updating node-sass to 5.0.0 solves this issue. Closing.

**Comment by rachejazz** [comment]
This problem still persists. After updating node-sass, sass loader says:
`./src/assets/scss/style.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/scss/style.scss)
Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.`

Tried updating the sass-loader, but no luck there
