### ISSUE TITLE
How to incorporate this with an app that is already using react-router-dom?

### ISSUE THREAD

**Issue by armenic** [cruip/open-react-template#31]
Dear Developers,
Thank you so much for creating such a nice LP for startups. I tried and it looks beautiful.
Unfortunately I was not able to incorporate it with my existing app that is using react-router-dom. I already have bunch of existing paths specified and I do not see any way to incorporate your home page. I will appreciate if you can share an example where this is incorporated with other paths.

**Comment by pasqualevitiello** [comment]
Thank you for your kind words! Please see #27, I am pretty sure it might help.
