### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by adithyaakrishna** [cruip/open-react-template#34]
Dear Cruip Team,
When I try to run npm run build, I get this error. I'm still a beginner in React and I would appreciate any help regarding this 🚀 

**Error:**
Cannot read property 'toLowerCase' of undefined
CompileError: Begins at CSS selector .invert-color .form-checkbox input:checked, .invert-color .form-radio input:checked

**Screenshot:**
![image](https://user-images.githubusercontent.com/23498248/104127281-4946d000-5387-11eb-9dfb-e0a61d153cb8.png)

**Comment by pasqualevitiello** [comment]
Did you change anything in Sass files? Just asking because I am not getting any error like that when building

**Comment by adithyaakrishna** [comment]
@pasqualevitiello  Yes, there was an warning regarding the unquote() thing in _mixin.css but I reverted it back

To be exact, I'm facing this issue when the file is being built/deployed in Netlify

![image](https://user-images.githubusercontent.com/23498248/104340078-5649f780-551e-11eb-82ea-fb1c03ee9e36.png)

**Comment by pasqualevitiello** [comment]
Can I close this ticket?

**Comment by adithyaakrishna** [comment]
@pasqualevitiello Yes, the error was with one package, I updated it and it was resolved 💯 

Thank you for your time and I totally love Cruip's Templates 🚀

**Comment by carlospence** [comment]
@adithyaakrishna Which package caused that error. Am currently having the same issue and I only worked on the unquote thing which I have also reversed but same issue.

**Comment by adithyaakrishna** [comment]
@carlospence It was related to react-router-dom

**Comment by abid-mugdho9875** [comment]
I have also face the problem.I was not complete one css tag.
