### ISSUE TITLE
Fails to install dependencies

### ISSUE THREAD

**Issue by FlexCode29** [cruip/open-react-template#38]
I made a pastebin of the error npm returns when installing the dependencies https://pastebin.com/eeLDGLAB

**Comment by pasqualevitiello** [comment]
Hello, it should work with node 14 and npm 6

**Comment by FlexCode29** [comment]
alright, the problem was that the node-sass wasn't up to date, sorry for opening the issue. Anyway the template works in node 16 and npm 7

**Comment by pasqualevitiello** [comment]
Great!
