### ISSUE TITLE
Source map error: Error: NetworkError when attempting to fetch resource.    : browser-polyfill.js.map

### ISSUE THREAD

**Issue by jhave** [cruip/open-react-template#4]
Appreciate you releasing this template. 

Unfortunately, site loads locally perfectly. But on server, console reports:

> Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://d9a3913d-909e-054a-8001-d5214d0468ea/browser-polyfill.js
Source Map URL: browser-polyfill.js.map

Any suggestions? (Note: I'm new to React. Searched for answers online but found none: perhaps I damaged the template when making changes.)

Thanks in advance!

Jhave

**Comment by pasqualevitiello** [comment]
Hey @jhave, I can't reproduce the issue, I am sorry. I'd recommend that you try with cloning the repository again and, reopen the issue if the error persists. Thanks!
