### ISSUE TITLE
Open Pro issue

### ISSUE THREAD

**Issue by James-Mart** [cruip/open-react-template#46]
I'd submit a PR if open pro were open source, but you have an issue in Tabs.js:

    const heightFix = () => {

        if (tabs.current.children[tab]) {

             tabs.current.style.height = tabs.current.children[tab - 1].offsetHeight + "px";
 
        }

    };

The issue is the children[tab] should be children[tab-1].

Thanks,
James

**Comment by pasqualevitiello** [comment]
Thank you James, I am going to release an update :)
