### ISSUE TITLE
SUper nice thee, but wonder why react for a single page?

### ISSUE THREAD

**Issue by schroef** [cruip/open-react-template#5]
Super ncei theme and love the colors, nice simple layer, works flawless.

I was looking a bit into this repo and keep wondering, why use react to make such single-page website. Doesnt that make a single page way to complicated?

**Comment by pasqualevitiello** [comment]
Hello @schroef,

I am glad you like the design (kudos to @davidepacilio, the designer).

I see your point, but it looks like that many developers feel more comfortable with React.  In addition, one might need to integrate a landing page like this into a more complex project, that is entirely built with React.

There was an interesting discussion around this subject on HN that is worth a look :) https://news.ycombinator.com/item?id=22888943
