### ISSUE TITLE
Requires Node 14 to run

### ISSUE THREAD

**Issue by tyayers** [cruip/open-react-template#50]
This template is really great, but I could only get "npm install" to run successfully with Node 14 (not with current LTS 16).  With Node 16 lots of errors are returned, would be helpful to document in the Readme as a prerequisite, or update the source code to Node 16.

Awesome work though, thanks for creating this!  Happy to upload logs from "npm install" with Node 16 if needed, however is easy to reproduce with a fresh clone.

**Comment by pasqualevitiello** [comment]
We'll likely release an update in the next months to support Node >14. Note that you can handle multiple node versions with NVM: https://github.com/nvm-sh/nvm and use Node 14, it’s pretty straightforward.
Here are the steps to install NVM: https://github.com/nvm-sh/nvm#install--update-script
