### ISSUE TITLE
Strange SassError?

### ISSUE THREAD

**Issue by mattwbdv** [cruip/open-react-template#51]
Thank you so much for this awesome template! One thing - I've been using it for a little while and never run into issues (aside from some occasional package upgrades as necessary). When developing today, though, I started getting: 
SassError: $string: null is not a string.

`SassError: $string: null is not a string.
  ╷
3 │     font-family: unquote(get-font-family($elem));
  │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/assets/scss/core/abstracts/_mixins.scss 3:15  font-family()
  src/assets/scss/core/base/_typography.scss 21:2   @import`

Trying to get up to speed with the scss here, and wondering if anyone else is seeing the same? Maybe just a webpack issue in my config? 

Anyways, thanks again! Please close this if this is not something others are experiencing.

**Comment by pasqualevitiello** [comment]
It sounds weird, can you please set a font for heading on this line? https://github.com/cruip/open-react-template/blob/master/src/assets/scss/settings/base/_typography.scss#L8

Replace line with this:
`heading: '"Inter", sans-serif',`

**Comment by mattwbdv** [comment]
that worked, thank you!
