### ISSUE TITLE
SCSS error.  Not compatible with latest Node versions

### ISSUE THREAD

**Issue by ashwath20** [cruip/open-react-template#54]
./src/assets/scss/style.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/scss/style.scss)
SassError: $string: null is not a string.
  ╷
3 │     font-family: unquote(get-font-family($elem));
  │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\scss\core\abstracts\_mixins.scss 3:15  font-family()
  src\assets\scss\core\base\_typography.scss 21:2   @import
  ../assets\scss\style.scss 38:9                                        root stylesheet

**Comment by pasqualevitiello** [comment]
I'd recommend to use Node 14 or 15.
You can handle multiple node versions with NVM: https://github.com/nvm-sh/nvm and use Node 14 or 15.
