### ISSUE TITLE
Provide a simple basic guide how to deploy to major cloud hosting sites

### ISSUE THREAD

**Issue by marcolino** [cruip/open-react-template#6]
A simple basic guide how to deploy to major cloud hosting sites (say: AWS/Heroku/Github pages/Gitlab pages) should be welcome.

I ask because I did try to deploy to gitlab pages following basic indications compiling a .gitlab-ci.yml file and faced a lot of hurdles and errors.

**Comment by pasqualevitiello** [comment]
I used Netlify for the demo. Web is plenty of tutorials, for example https://www.youtube.com/watch?v=JwWvD_fWJFY

**Comment by marcolino** [comment]
I did try a netflix deploy. I am getting the same errors as with gitlab pages deploy:

```
Loading failed for the <script> with source “https://modest-hopper-edbcd7.netlify.app/dist/static/js/2.937d5458.chunk.js”. modest-hopper-edbcd7.netlify.app:1:1
Loading failed for the <script> with source “https://modest-hopper-edbcd7.netlify.app/dist/static/js/main.1549df56.chunk.js”.
```

The problem is that 'dist/' folder which is not in the real build path... But it's not clear to me how to solve... Is it possibly necessary to eject?

These are the kind of problems I was referring to when I asked for some deploy directions...

And, more, some instructions about the customization should be welcome... At least some links pointing to the details of main packages you used...
