### ISSUE TITLE
Anchor Links Not Working

### ISSUE THREAD

**Issue by elephanted** [cruip/open-react-template#60]
Hello - it appears that anchor links to scroll down the page are do not work. Should anchor links be expected to work with the Smooth Scroll effect? At the moment anchors appear to not work at all.

**Comment by pasqualevitiello** [comment]
There is no smooth scroll functionality: header links are supposed to open new pages, which are missing because this is the free version of Open PRO: https://cruip.com/  

Hope that makes sense :)
