### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by urbanslug** [cruip/open-react-template#7]
Could just be me but what's the license on this project? Could it be made explicit?

The package.json has [private set to true](https://github.com/cruip/open-react-template/blob/master/package.json#L4) but according to the package.json spec that's not a license.
_"Consider also setting "private": true to prevent accidental publication."_

Edit:
Just ran the project and the bottom of the page says _"Made by Cruip. All right reserved"_ so I guess it's not public. It would still be nice if it was clearer.

Edit 2:
FWIW: The name **open-react-template** is quite misleading given it's not (that) open.

**Comment by marcolino** [comment]
I agree totally. Please be more explicit...

**Comment by pasqualevitiello** [comment]
The license is specified in the README.md file: https://github.com/cruip/open-react-template#terms-and-license

**Comment by Zenahr** [comment]
@pasqualevitiello usually you can add a LICENSE.md file which makes it so that people see the license used right away. It's common practice.
