### ISSUE TITLE
Hello, which node.js version are you using in the project?

### ISSUE THREAD

**Issue by RaveHunter05** [cruip/open-react-template#70]
Hello, good morning. Which version of node js are you currently using in the project? i tried to install it with npm and with yarn and it was impossible, gave me tons of errors. I was using v16.13.0

**Comment by RaveHunter05** [comment]
Found that the error was an incompatibility between the jest versions, i was able to start the app by adding this to the a .env file in the root dir

```SKIP_PREFLIGHT_CHECK=true```

Btw, i don't believe this is a correct solution, maybe you should add the version of jest in the package.json

**Comment by Shamsa-Ali** [comment]
It will run on node version 10.24.1 without facing any problems

**Comment by pasqualevitiello** [comment]
I recommend node 14
