### ISSUE TITLE
Error implementing components

### ISSUE THREAD

**Issue by jimbo1990** [cruip/open-react-template#74]
Hi when I try to implement components such as Carousel I am getting the following error messages:

`./src/views/About.js`
 ` Line 20:12:  'Carousel' is not defined      react/jsx-no-undef`
 `  Line 21:4:   'CarouselItem' is not defined  react/jsx-no-undef`
 `  Line 22:4:   'CarouselItem' is not defined  react/jsx-no-undef`
 `  Line 23:4:   'CarouselItem' is not defined  react/jsx-no-undef`
`   Line 24:4:   'CarouselItem' is not defined  react/jsx-no-undef`

I understand that this is probably because I am not calling the Carousel component into my About.js file however I am unusre how to call this. The same happens with all componets. I am using the following code:

`import React from 'react';`
`import GenericSection from '../components/sections/GenericSection';`
`import SectionHeader from '../components/sections/partials/SectionHeader';`
`import Cta from '../components/sections/Cta';`

`class About extends React.Component {`
`  render() {`
  
`    const sectionHeader = {`
 `     title: 'About us'`
`    }`
  
`    return (`
`      <React.Fragment>`
`        <GenericSection>`
`          <SectionHeader data={sectionHeader} className="center-content" />`
`          <p>`

`          <Carousel>`
`  <CarouselItem>Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.</CarouselItem>`
`  <CarouselItem>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</CarouselItem>`
`  <CarouselItem>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.</CarouselItem>`
`  <CarouselItem>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</CarouselItem>`
`</Carousel>`

  `        </p>`
 `       </GenericSection>`
`        <Cta topDivider split />`
`      </React.Fragment>`
`    );`
`  }`
`}`
`export default About;`

Please forgive me if this is posted in the wrong place I am an abosolute begginer at react.

Thank you in advance for any help.

**Comment by pasqualevitiello** [comment]
Hi! You're not importing all required components :) For more information: https://create-react-app.dev/docs/importing-a-component/

**Comment by jimbo1990** [comment]
Thanks yeah thats what I thought but im still in a bit of a rut the code on the website doesn't actually work because there is no Accordion component/element under the src/components/elements folder in cruip same goes for Carousel and others. If you could give me a simple example of how to import the Accordion for example I would greatly appreciate it. Again thanks in advance.

**Comment by pasqualevitiello** [comment]
Well, this free template doesn't come with any carousel or accordion components, I thought you wanted to import your own components :)
