### ISSUE TITLE
Blank After Install: Uncaught TypeError: ansiStyles.color is undefined

### ISSUE THREAD

**Issue by mnutsch** [cruip/open-react-template#81]
After installing this repo the app did not launch properly.

I did the following:
cloned the repo to my local PC
ran "npm install"
ran "npm start"

The command prompt indicates that the server starts and a web browser tab opens to localhost:3000.
However, the web page is blank. 
The following error message is shown in the browser console:

Uncaught TypeError: ansiStyles.color is undefined
    js index.js:72
    js 0.chunk.js:22755
    Webpack 13

**Comment by Vansh-Baghel** [comment]
Hey @mnutsch, try to use npm run dev as mentioned in the Readme
