### ISSUE TITLE
Module Parse Error 

### ISSUE THREAD

**Issue by rohitbhat1603** [cruip/open-react-template#87]
./components/ui/mobile-menu.tsx
Module parse failed: Bad character escape sequence (2:94)
| import { createProxy } from "next/dist/build/webpack/loaders/next-flight-loader/module-proxy"
> const proxy = createProxy("......\open-react-template-master\components\ui\mobile-menu.tsx")

**Comment by Jarvisbruder** [comment]
Also encountered same issue, persisting despite erasing the component "mobile-menu.tsx" and dependencies

**Comment by programmablewealth** [comment]
@rohitbhat1603 @Jarvisbruder are you on Windows? I was and I had this issue.

It was fixed by upgrading nextjs to version 13.3.1-canary.4

https://github.com/vercel/next.js/discussions/47736#discussioncomment-5576280
