### ISSUE TITLE
After reloading the page, the page scrolls down a little

### ISSUE THREAD

**Issue by shubhankar30** [cruip/open-react-template#9]
Thank you for the free theme. Loving it.  Leaning towards buying the premium soon.

After you refresh the page, the y scrollbar scrolls a little. Can't seem to find the offset setting within the code. 

Thanks.

**Comment by pasqualevitiello** [comment]
Hey @shubhankar30 just noticed it, thank you for reporting! 

That might have to do with the scroll-reveal component. Anyway, it's not a big deal, since it is not really annoying, and there is not really a reason to refresh the page - it's a one-page template :)

**Comment by shawnli789** [comment]
I have this issue too. Even though users might not constantly refresh the page, still this is a unexpected behavior and it would be great if someone can fix this.

Thanks
