### ISSUE TITLE
Redirecting to different pages

### ISSUE THREAD

**Issue by SxMAbel** [cruip/open-react-template#95]
Using your code, I want to know how to redirect, 

Ex: user types in data and click a button, after clicking the button it verifies that the data, next if verification complete it will send them to a different page.

I've tried:

`import { useRouter } from 'next/navigation'`
`import { redirect } from 'next/navigation'`

**Comment by rohan9607** [comment]
"use client"
import { useRouter } from 'next/navigation'

const handleClick = (e : any) => {
 const {name, value} = e.target;
...Verify Data

if(verified){
router.push("/destination")
}

**Comment by MrBlackGhostt** [comment]
if it not solve i want to work on it
